CREATE TABLE league.TEAM(
      ID VARCHAR (64) NOT NULL,
      DUMMY VARCHAR (64),
      PRIMARY KEY (ID)
);

CREATE TABLE league.FIXTURE(
       ID  INT  NOT NULL AUTO_INCREMENT,
       GAME_WEEK INT unsigned,
       TEAM_1 VARCHAR (64) NOT NULL,
       TEAM_2 VARCHAR (64) NOT NULL,
       FIXTURE_DATE DATETIME,
       TEAM_1_SCORE INT unsigned,
       TEAM_2_SCORE INT unsigned,
       TEAM_1_POINTS INT unsigned,
       TEAM_2_POINTS INT unsigned,
       FOREIGN KEY(TEAM_1) REFERENCES league.TEAM(ID),
       FOREIGN KEY(TEAM_2) REFERENCES league.TEAM(ID),
       CONSTRAINT UniqueMatch UNIQUE (TEAM_1, TEAM_2),
       PRIMARY KEY (ID)
);

CREATE TABLE league.PLAYER(
       ID   INT NOT NULL AUTO_INCREMENT,
       TEAM_NAME VARCHAR (64) NOT NULL,
       NAME VARCHAR (64)  NOT NULL,
       POSITION VARCHAR (64),
       GOALS_SCORED INT unsigned,
       FOREIGN KEY(TEAM_NAME) REFERENCES league.TEAM(ID),
       PRIMARY KEY (ID)
);

CREATE TABLE league.GOAL(
      ID INT NOT NULL AUTO_INCREMENT,
      MATCH_ID INT NOT NULL,
      PLAYER_ID INT NOT NULL,
      FOREIGN KEY(MATCH_ID) REFERENCES league.FIXTURE(ID),
      FOREIGN KEY(PLAYER_ID) REFERENCES league.PLAYER(ID),
      PRIMARY KEY (ID)
);

CREATE TABLE league.IMPORT_LOG(
      ID INT NOT NULL AUTO_INCREMENT,
      STATUS VARCHAR (64) NOT NULL,
      MODEL VARCHAR (64) NOT NULL,
      DATE_TIME DATETIME NOT NULL,
      NOTICES TEXT,
      WARNINGS TEXT,
      ERRORS TEXT,
      PRIMARY KEY (ID)
);