CREATE TABLE league.POINT(
      VALID_VALUES INT unsigned NOT NULL,
      PRIMARY KEY (VALID_VALUES)
);

INSERT INTO league.POINT VALUES (0), (1), (3);

CREATE TABLE league.TEAM(
       NAME VARCHAR (64) NOT NULL,
       PRIMARY KEY (NAME)
);

CREATE TABLE league.FIXTURE(
       MATCH_ID  INT  NOT NULL AUTO_INCREMENT,
       GAME_WEEK INT unsigned,
       TEAM_1 VARCHAR (64) NOT NULL,
       TEAM_2 VARCHAR (64) NOT NULL,
       FIXTURE_DATE DATETIME,
       TEAM_1_SCORE INT unsigned,
       TEAM_2_SCORE INT unsigned,
       TEAM_1_POINTS INT unsigned,
       TEAM_2_POINTS INT unsigned,
       FOREIGN KEY(TEAM_1) REFERENCES league.TEAM(NAME),
       FOREIGN KEY(TEAM_2) REFERENCES league.TEAM(NAME),
       FOREIGN KEY(TEAM_1_POINTS) REFERENCES league.POINT(VALID_VALUES),
       FOREIGN KEY(TEAM_2_POINTS) REFERENCES league.POINT(VALID_VALUES),
       PRIMARY KEY (MATCH_ID)
);

CREATE TABLE league.PLAYER(
       PLAYER_ID   INT NOT NULL AUTO_INCREMENT,
       TEAM_NAME VARCHAR (64) NOT NULL,
       FIRST_NAME VARCHAR (64)  NOT NULL,
       LAST_NAME VARCHAR (64),
       POSITION VARCHAR (64),
       GOALS_SCORED INT unsigned,
       FOREIGN KEY(TEAM_NAME) REFERENCES league.TEAM(NAME),
       PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE league.GOAL(
      GOAL_ID INT NOT NULL AUTO_INCREMENT,
      MATCH_ID INT NOT NULL,
      PLAYER_ID INT NOT NULL,
      FOREIGN KEY(MATCH_ID) REFERENCES league.FIXTURE(MATCH_ID),
      FOREIGN KEY(PLAYER_ID) REFERENCES league.PLAYER(PLAYER_ID),
      PRIMARY KEY (GOAL_ID)
);